# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [3]:
import numpy as np

a = np.arange(6)

print(a.sum()) #是陣列專有的函式
print(np.sum(a)) #是陣列專有的函式
print(sum(a)) #是python內建的函式，所有型態皆可以使用
#差別在於定義在np或是python底下

15
15
15


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [4]:
# 記得先 Import 正確的套件
import numpy as np

In [7]:
A = np.random.random((5, 5))

print(A)
print(np.max(A)) #找最大值
print(np.min(A)) #找最小值
B=(A-np.min(A))/(np.max(A)-np.min(A))#正規化
print(B)

[[0.15833381 0.11495846 0.74356356 0.94839048 0.40600702]
 [0.71445359 0.90174477 0.31941311 0.35913545 0.16169363]
 [0.35345859 0.16757521 0.38265767 0.05081245 0.29848194]
 [0.97807289 0.79930874 0.92423826 0.63660978 0.13140888]
 [0.36214876 0.50470454 0.11629331 0.24809813 0.1891274 ]]
0.9780728914755868
0.050812448049289416
[[0.11595595 0.06917799 0.74709443 0.96798913 0.38305804]
 [0.71570091 0.91768427 0.28967122 0.3325096  0.11957933]
 [0.32638742 0.12592229 0.35787704 0.         0.26709809]
 [1.         0.80721258 0.94194228 0.63175059 0.08691887]
 [0.3357593  0.48949795 0.07061755 0.21276189 0.14916516]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [9]:
A = np.random.random(10)
A=np.random.random(10)
print(A)
A_MAX=np.max(A)
print(A_MAX)
print(np.argmax(A))
A[np.argmax(A)]=-1
print(A)

[0.84264841 0.12379812 0.54947497 0.95251858 0.08395043 0.49908287
 0.9855031  0.46673727 0.99902599 0.56799628]
0.999025988935489
8
[ 0.84264841  0.12379812  0.54947497  0.95251858  0.08395043  0.49908287
  0.9855031   0.46673727 -1.          0.56799628]
