# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [15]:
# 記得先 Import 正確的套件
import numpy as np

In [16]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
print(Z)

[[[0 5 1 ... 5 8 5]
  [2 9 3 ... 4 3 0]
  [6 8 6 ... 2 5 3]
  ...
  [2 8 9 ... 5 9 7]
  [6 9 3 ... 5 3 5]
  [6 4 0 ... 5 9 4]]

 [[0 5 7 ... 1 2 4]
  [5 8 0 ... 7 5 2]
  [9 9 5 ... 5 9 5]
  ...
  [5 4 3 ... 0 8 6]
  [9 2 2 ... 9 6 7]
  [9 1 4 ... 4 7 3]]

 [[7 8 1 ... 2 2 5]
  [2 6 0 ... 5 3 9]
  [1 2 2 ... 1 1 7]
  ...
  [3 6 7 ... 4 5 1]
  [4 7 9 ... 0 2 7]
  [7 8 7 ... 5 8 2]]

 ...

 [[2 6 7 ... 6 8 0]
  [1 7 2 ... 7 2 5]
  [4 8 2 ... 2 8 1]
  ...
  [7 6 8 ... 7 3 5]
  [3 1 5 ... 1 6 5]
  [9 7 1 ... 0 5 2]]

 [[2 4 1 ... 1 1 1]
  [9 3 3 ... 5 6 0]
  [8 6 0 ... 2 1 1]
  ...
  [0 9 8 ... 0 0 0]
  [8 7 4 ... 5 0 5]
  [8 2 1 ... 2 1 7]]

 [[4 4 0 ... 7 8 6]
  [8 1 6 ... 4 8 1]
  [8 7 2 ... 0 0 2]
  ...
  [7 7 8 ... 8 7 7]
  [2 2 7 ... 2 4 8]
  [2 4 3 ... 0 2 3]]]


In [17]:
%timeit -n 10 a = 2

for data in Z:
    for row in data:
        for a in row:
            a+=1
#迴圈一層一層運算每一個元素 速度最慢

24.3 ns ± 7.28 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [18]:
%timeit -n 10 a = 2

for i in Z.flat:
    i+=1
#攤平才可迭代每一個元素

24.3 ns ± 7.28 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [19]:
%timeit -n 10 a = 2

Z += 1
#陣列廣播性質運算速度最快

24.3 ns ± 9.04 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [5]:

Z = np.random.randint(0,10,50)
print(Z)


[8 2 0 7 1 8 1 6 3 8 8 8 8 4 5 7 5 6 8 4 0 4 8 9 0 3 1 4 6 9 9 4 4 6 6 2 4
 6 8 8 3 8 2 3 5 5 1 8 3 8]


In [22]:
from scipy import stats

Z = np.random.randint(0,10,50)
print(Z)
mode = stats.mode(Z)[0][0]
print('頻率最高數值:', mode)

[1 1 0 5 5 1 3 1 6 7 2 6 2 2 7 0 4 6 7 7 7 1 9 3 1 0 0 8 1 1 9 0 5 4 2 5 6
 4 8 8 6 8 1 7 5 5 8 1 7 9]
頻率最高數值: 1


In [23]:
print('頻率最高數值之位置:', np.searchsorted(Z, mode))

頻率最高數值之位置: 27


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [24]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[3, 6, 2, 7, 5, 1]
[3, 6, 2, 7, 5, 1]
[[1, 2, 5, 9], [0, 8, 9, 9], [4, 2, 3, 2]]
[array([1, 2, 5, 9]), array([0, 8, 9, 9]), array([4, 2, 3, 2])]
[[[6, 2], [9, 4], [4, 2]], [[1, 8], [2, 6], [6, 5]]]
[array([[6, 2],
       [9, 4],
       [4, 2]]), array([[1, 8],
       [2, 6],
       [6, 5]])]


In [ ]:
'''
Your Code
'''